version: "3"

services:

  db_deploy:
    image: postgres
    networks:
      - backend_deploy
    volumes:
      - dbdata_deploy:/var/lib/postgresql/data
    restart: unless-stopped

  web_deploy:
    build:
      context: .
      dockerfile: Dockerfile-deploy
    environment:
      - DATABASE={"host":"db", "password":"postgres"}
    networks:
      - backend_deploy
    ports:
      - "8000:80"
    depends_on:
      - db_deploy
    tty: true
    restart: unless-stopped

networks:
  backend_deploy:

volumes:
  dbdata_deploy: